// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGQuGMIuaj9EdlkE7bd-J50uaCSEZxwww',
    appId: '1:774978931841:web:a08ed3c0143e167c70d180',
    messagingSenderId: '774978931841',
    projectId: 'huabao-recruitment',
    authDomain: 'huabao-recruitment.firebaseapp.com',
    storageBucket: 'huabao-recruitment.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbax2WkqHaIejCC_9PLtuXoLw_FEPmStA',
    appId: '1:774978931841:android:083db14320334a8070d180',
    messagingSenderId: '774978931841',
    projectId: 'huabao-recruitment',
    storageBucket: 'huabao-recruitment.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEZdJ1Xg30iF6Rl5KxZEI9b8fhA_rsaiM',
    appId: '1:774978931841:ios:0c25542c866d183070d180',
    messagingSenderId: '774978931841',
    projectId: 'huabao-recruitment',
    storageBucket: 'huabao-recruitment.firebasestorage.app',
    iosBundleId: 'com.example.recruitmentMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEZdJ1Xg30iF6Rl5KxZEI9b8fhA_rsaiM',
    appId: '1:774978931841:ios:0c25542c866d183070d180',
    messagingSenderId: '774978931841',
    projectId: 'huabao-recruitment',
    storageBucket: 'huabao-recruitment.firebasestorage.app',
    iosBundleId: 'com.example.recruitmentMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGQuGMIuaj9EdlkE7bd-J50uaCSEZxwww',
    appId: '1:774978931841:web:249f5a12376cd97a70d180',
    messagingSenderId: '774978931841',
    projectId: 'huabao-recruitment',
    authDomain: 'huabao-recruitment.firebaseapp.com',
    storageBucket: 'huabao-recruitment.firebasestorage.app',
  );
}
